# fly.toml file generated for autodelete on 2023-03-05T21:44:39+05:30

app = "autodelete"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true


[mounts]
  source = "data"
  destination = "/data"
